---
# An example configuration file detailing all options that can be set.
# The layout is strongly intended to mimic the graphical menus that expose these settings.

# This can be found not in 'Settings...' but under 'Project Structure...'
projectSettings:
  project:
    projectName: project-name-in-intellij
    projectSdk: ProjectSDK
    projectLanguageLevel: '8'
  modules:
    - name: my-module
      sources:
        # If relative, this will be evaluated with respect to the project.
        - contentRoot: path/to/module
          # Note that folders listed here are merely appended to the existing list;
          # we do NOT clear out all folders first.
          sources:
            - src/main/kotlin
          tests:
            - src/it/java
          resources:
            - src/main/other_resources
          testResources:
            - src/test/other_resources
          excluded:
            - src/main/resources/too_large_to_index

editor:
  codeStyle:
    java:
      imports:
        classCountToUseImportWithWildcard: 999
        namesCountToUseStaticImportWithWildcard: 999
  general:
    autoImport:
      java:
        optimizeImportsOnTheFly: true
        excludeFromImportAndCompletion:
          - com.google.inject.Inject
          - com.sun.istack.internal.Nullable
          - edu.umd.cs.findbugs.annotations.Nullable
  spelling:
    dictionaries:
      # files containing a word on each line to be used as custom spelling dictionaries.
      - relative_to_project.dic
      - /tmp/absolute.dic

buildExecutionDeployment:
  buildTools:
    maven:
      importing:
        vmOptionsForImporter: -Xmx1g
      mavenHomeDirectory: /usr
  compiler:
    addRuntimeAssertionsForNotnullAnnotatedMethodsAndParameters: false
    buildProcessHeapSizeMbytes: 1024
  requiredPlugins:
    - plugin: CheckStyle-IDEA
      minimumVersion: 5.23.0
      maximumVersion: 5.24.1

otherSettings:
  checkstyle:
    checkstyleVersion: "8.16"
    # Manages the files that Checkstyle verifies. Can be one of:
    # - Only Java sources (but not tests)
    # - Only Java sources (including tests)
    # - All sources (but not tests)
    # - All sources (including tests)
    # - All files in project
    scanScope: Only Java sources (including tests)
    treatCheckstyleErrorsAsWarnings: false
    configurationFiles:
      - active: true
        description: Project Checkstyle Configuration
        # Can be one of:
        # - a local file
        # - an HTTP URL
        # - 'bundled' (with description matching the bundled description, e.g. "Google Checks")
        file: checkstyle.xml

# Run / Debug configurations
configurations:
  remote:
    - name: Debug
      configuration:
        host: localhost
        port: 5005
