java_library(
    name = "codestyle",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/github/alexandrecarlton/idea/settings/applier/api",
        "//src/main/java/com/github/alexandrecarlton/idea/settings/layout/editor/codestyle",
        "//src/main/java/com/github/alexandrecarlton/idea/settings/layout/editor/codestyle/java",
        "@idea-IC//:lib/platform-api",
    ],
)
