java_library(
    name = "general",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/github/alexandrecarlton/idea/settings/applier/api",
        "//src/main/java/com/github/alexandrecarlton/idea/settings/layout/editor/general",
        "//src/main/java/com/github/alexandrecarlton/idea/settings/layout/editor/general/auto_import",
        "//third_party/maven/javax/inject:javax_inject",
    ],
)
