ersion: 2
jobs:
  build:
    docker:
      - image: alexandrecarlton/bazel:0.23.0
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: bazel build //:idea-settings
