ersion: 2
jobs:
  build:
    docker:
      - image: alexandrecarlton/bazel:0.23.0
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout

      - restore_cache:
          key: circle-ci-idea-settings

      - run: bazel build //:idea-settings

      - save_cache:
          paths:
            - ~/.cache/bazel
          key: circle-ci-idea-settings
