---
version: 2
jobs:
  build:
    docker:
      # Bazel doesn't work on alpine, even if we have libc6-compat, libstdc++ and libgcc
      - image: ubuntu:19.04
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      - restore_cache:
          key: circle-ci-idea-settings

      - run:
          name: Download bazelisk
          command: |
            apt update
            apt install --yes curl pkg-config zip g++ zlib1g-dev unzip python python3.7 openjdk-8-jdk
            curl --location --output /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64
            chmod +x /usr/local/bin/bazel

      - run:
          name: Build idea-settings
          command: bazel build --jobs=1 //:idea-settings

      - run:
          name: Build idea-settings tests
          command: bazel build --jobs=1 //:tests

      - run:
          name: Test idea-settings
          command: bazel test --jobs=1 //:tests

      - run:
          name: Integration test idea-settings
          command: bazel test --jobs=1 //:integration-tests

      - run:
          name: Copy out bazel test results
          command: cp -r -L bazel-testlogs bazel-test-results
          when: always

      - store_artifacts:
          path: bazel-test-results

      - store_test_results:
          path: bazel-test-results

      - save_cache:
          paths:
            - ~/.cache/bazel
            - ~/.cache/bazelisk
          key: circle-ci-idea-settings
