version: 2
jobs:
  build:
    docker:
      - image: alexandrecarlton/bazel:0.23.0
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout

      - restore_cache:
          key: circle-ci-idea-settings

      - run:
          name: Build idea-settings
          command: bazel build //:idea-settings

      - run:
          name: Test idea-settings
          command: bazel test //:tests

      - run:
          name: Copy out bazel test results
          command: cp -r -L bazel-testlogs bazel-test-results
          when: always

      - store_test_results:
          path: bazel-test-results

      - save_cache:
          paths:
            - ~/.cache/bazel
          key: circle-ci-idea-settings
