java_library(
    name = "editor",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/github/alexandrecarlton/idea/settings/applier/editor/codestyle",
        "//src/main/java/com/github/alexandrecarlton/idea/settings/layout/editor",
        "@idea-IC//:lib/platform-api",
    ],
)
