java_library(
    name = "project_settings",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/github/alexandrecarlton/idea/settings/applier/api",
        "//src/main/java/com/github/alexandrecarlton/idea/settings/dagger/module",
        "//src/main/java/com/github/alexandrecarlton/idea/settings/layout/project_settings",
        "//src/main/java/com/github/alexandrecarlton/idea/settings/layout/project_settings/modules",
        "//src/main/java/com/github/alexandrecarlton/idea/settings/layout/project_settings/project",
        "//third_party/maven/javax/inject:javax_inject",
        "@idea-IC//:lib/platform-api",
    ],
)
