java_library(
    name = "configurations",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/github/alexandrecarlton/idea/settings/applier/api",
        "//src/main/java/com/github/alexandrecarlton/idea/settings/layout/configurations",
        "//src/main/java/com/github/alexandrecarlton/idea/settings/layout/configurations/remote",
        "//third_party/maven/javax/inject:javax_inject",
    ],
)
