java_library(
    name = "maven",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/github/alexandrecarlton/idea/settings/applier/api",
        "//src/main/java/com/github/alexandrecarlton/idea/settings/layout/build_execution_deployment/build_tools/maven",
        "//third_party/maven/javax/inject:javax_inject",
        "@idea-IC//:plugins/maven/lib/maven",
    ],
)
