java_library(
    name = "sql_dialects",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/github/alexandrecarlton/idea/settings/applier/api",
        "//src/main/java/com/github/alexandrecarlton/idea/settings/layout/languages_frameworks/sql_dialects",
        "//third_party/maven/javax/inject:javax_inject",
        "@idea-IC//:lib/platform-api",
        "@idea-IC//:lib/extensions",
        "@idea-IC//:lib/util",
        "@idea-IU//:plugins/DatabaseTools/lib/database-impl",
        "@idea-IU//:plugins/DatabaseTools/lib/database-openapi",
    ],
)
