java_library(
    name = "arrangement",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/github/alexandrecarlton/idea/settings/applier/api",
        "//src/main/java/com/github/alexandrecarlton/idea/settings/layout/editor/codestyle/java/arrangement",
        "//third_party/maven/javax/inject:javax_inject",
        "//third_party/maven/com/google/guava",
        "@idea-IC//:lib/platform-api",
    ],
)
